name: Frontend CI
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: ['dev', 'prod']

  # Allow for reuse call in deploy job
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  frontend-checks:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: install frontend dependencies
        run: npm ci
      - name: eslint
        run: npm run lint
      - name: typecheck
        run: npm run typecheck
      - name: build astro
        run: npm run build
      - name: vitest
        run: npm test -- run --coverage
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
